matrix:
  - [[MPI_VARIANT, 'openmpi']]
  - [[MPI_VARIANT, 'mpich']]
travis:
  secure:
    BINSTAR_TOKEN: RYKoqSoxnuwZGUaidXh7cjh01xJ+z1DTRF2oFXGD2S/bcV9dHXTKi8Oc2+trdGNXOtPoSfVZTKAlwbdeoL2SWEOlLJ42kpchgNnIMkmALY5zvWBXX8hBoLnwgV17LwdvVFNDJ8IzF6yyy+YgogMyC2tfgX5vG8+Ekjp7YfffBIXJy/zpl1508N9uZaFTPh20oB9wJgmr5jRIBV3GV8FNQjp5W6L2SnqAJAeUjPoQVnjozwQt2mzDkVIzXkkGSBHJhRnDM6oPjA/wV3GyOf+040+frO48rL4uBOV8vOO4v7XgiLOxDiBsiu1Q8gbbigrGuKUJidiny2+SnySmn89GrZGwRmhnqtYIG/1GkWLowJ2roR2btoCTRygZaR2pHgUITOizRy/zPQmQpZSzW07gFXu66OHknh5QdeGDvRUthyChDaJz4aQBHuTJPzo3aHRD+XXbdal149w7wCMTlmJeUvXhC9h8H06wpC6hG02UMVGhWFwnhIgeP8CsnXHT5zJsjVekd+J7hSV2GbN3nvpo1przIYToNbUog5wcGZVfxYZ47ygntO1tVNIQ1ee5wpvr1tWthakmed1eAqBRtCrokly7H9U2vN5O5FuR7AbcnBSeLXwuZVg1stYj93JeOWks30eW/vmSckeHNjBtAe9WjUfvkabzRPQcCKvdu7ocmpk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
